### ISSUE TITLE
Authentication endpoint changed

### ISSUE THREAD

**Issue by g71** [joelcassel/easee-js-slim#1]
Easee auth endpoint have changed from:
`/api/accounts/token`
to:
`/api/accounts/login`

Just updating this in initAccessToken() seem to work fine in my limited and local test.

**Comment by joelcassel** [comment]
Thanks for noticing. As part of the latest release the lib is now updated with the new token handling. Hopefully all is ok.

**Comment by g71** [comment]
Super, thanks!
