### ISSUE TITLE
Replace process.exit

### ISSUE THREAD

**Issue by g71** [joelcassel/easee-js-slim#2]
Hi,

Nice work!

The two process.exits in initAccessToken() are a bit evil though :-) I've been using this from Node-Red and a failure to authenticate terminates the entire service which is problematic.

I suggest to replace them with a "return undefined;" or possibly an exception to let the client manage the issue.

https://github.com/joelcassel/easee-js-slim/blob/a85262875a1a1d51c1d182b5e1fe4eb386564489/src/integration/easee.js#L36
https://github.com/joelcassel/easee-js-slim/blob/a85262875a1a1d51c1d182b5e1fe4eb386564489/src/integration/easee.js#L51

**Comment by joelcassel** [comment]
Thanks, it depends on usecase, much better to throw. Updated in 1.1.0
