### ISSUE TITLE
Suggestion: add updateWeeklySchedule()

### ISSUE THREAD

**Issue by g71** [joelcassel/easee-js-slim#3]
It is possible to read the weekly schedule, and it would be nice to be able to update it as well. I am using it schedule the cheapest hours for charging.

Leveraging the same pattern as used elsewhere:

```
  // https://api.easee.cloud/api/chargers/{id}/weekly_charge_plan
  async updateWeeklySchedule(
    settingsJsonObjToUpdate = {},
    chargerId = this.onlyOneChargerId,
  ) {
    const response = await this.easeePostCall(
      `/api/chargers/${chargerId}/weekly_charge_plan`,
      settingsJsonObjToUpdate,
    )
    return summarizeUpdateResult(response)
  }
```

**Comment by joelcassel** [comment]
Added to 1.1.0 , please feel free to do PRs as well in case you already have the code. 

Also note that the updating responsiveness from me today is very unusual, issues will be fixed eventually in a few weeks normally.

**Comment by g71** [comment]
Thanks! Will do a PR next time! The hack is a nice trick as the way of starting and stopping charging is harder than you would expect.
