### ISSUE TITLE
API base URL will change

### ISSUE THREAD

**Issue by chrisill** [joelcassel/easee-js-slim#4]
According to [https://developer.easee.cloud/docs](url) easee is changing the base API URL by end of August 2023

> ... we have updated the base API URL from api.easee.cloud to api.easee.com. 
> The api.easee.cloud domain will reach its end of life on September 1st 2023. The api.easee.com domain is already active and we recommend users to update the URL at the earliest convenience.

Thank you for updating the module, Joel!
Chris

**Comment by joelcassel** [comment]
Updated api and doc domain in v1.2.0, all should be good now i think. ( Allthough the documentation domain is not updated yet)
Thanks for the reminder and your patience.
